### ISSUE TITLE
Mattermoz doesn't scroll when someone talks

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mattermoz#42] opened 2016-02-12 00:00 UTC
... which means every time a message comes in you will have to manually scroll down to the bottom of the page to see it.

**Comment by alanmoo** [comment] 2016-03-15 22:46
If the user has previously scrolled up, this makes sense as a behavior. But the problem I've seen in the past (though have been unable to consistently replicate) is that sometimes I'm at the bottom and new messages come in without scrolling, or there's no indication that there are new messages since I scrolled up.

**Comment by alanmoo** [comment] 2016-03-15 23:39
Relevant JIRA tickets upstream:
https://mattermost.atlassian.net/browse/PLT-1021
https://mattermost.atlassian.net/browse/PLT-1815

**Comment by alanmoo** [comment] 2016-03-16 21:55
1815 (linked above) was turned into https://mattermost.atlassian.net/browse/PLT-1917, and I think that's the one I should solve to fix the usability (though 1021 might also be useful).

**Comment by gideonthomas** [comment] 2016-03-23 21:04
This is impossible to reproduce. It seems to have nothing to do with losing focus or switching channels. I also do not really see anything obviously wrong in their code. Have either of you @alanmoo or @mmmavis noticed this recently? If so, can you post the STR?

**Comment by alanmoo** [comment] 2016-03-23 21:35
It's kind of like a peripheral vision issue- you don't quite notice it when you're looking straight at it, it's strange UX. That being said, I think addressing https://mattermost.atlassian.net/browse/PLT-1917 will make progress towards negating the heart of the issue, which is users not realizing there are new messages to read.

**Comment by alanmoo** [comment] 2016-04-04 14:52
Submitted at https://github.com/mattermost/platform/pull/2612

**Comment by alanmoo** [comment] 2016-04-11 14:10
🎉This has been merged in upstream, will be a part of the May release! 🎉

**Closed as completed by alanmoo** 2016-04-11 14:10 UTC
Labels: bug

**Comment by Pomax** [comment] 2016-04-11 16:44
awesome!
